routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');

    return 'Commands run successfully Cleared.';
});
Route::get('/', function () {

    return view('welcome');

})->name('index');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/about-us', 'FrontendController@about')->name('about');
Route::get('/services', 'FrontendController@services')->name('services');
Route::get('/contact-us', 'FrontendController@contactUs')->name('contact-us');

Route::get('forget-password', 'AccountController@getEmail');
Route::post('forget-password', 'AccountController@postEmail');
Route::get('reset-password/{token}', 'AccountController@getPassword');
Route::post('reset-password', 'AccountController@updatePassword');


Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/galleries', 'Backend\GalleryController');
        Route::post('single/gallery/delete', 'Backend\GalleryController@destroyGallery')->name('single.gallery.destroy');
        Route::resource('/features', 'Backend\FeatureController');
        Route::resource('/general', 'Backend\GeneralController', [
            'only' => ['index', 'store']
        ]);
        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'update']
        ]);
    });
});

app/General.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class General extends Model
{
    protected $table = "generals";
    protected $guarded = [];

}

app/Http/Controllers/Backend/FeatureController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Feature;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;


class FeatureController extends Controller
{


    public function index()
    {
        $features = Feature::orderBy('id', 'ASC')->get();
        return view('backend.features.index', compact('features'));
    }

    public function create()
    {
        return view('backend.features.create');
    }

    public function store(Request $request)
    {

        $this->validate($request, [
            'title' => 'required',
            'value' => 'required',

        ], [
            'title.required' => 'Title is required.',
            'value.required' => 'Value is required.',
        ]);


        $feature = Feature::create([
            'title' => $request->title,
            'value' => $request->value,
        ]);

        return redirect()->route('admin.features.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Feature created successfully.'
            ]);
    }

    public function edit($id)
    {
        $feature = Feature::find($id);
        return view('backend.features.edit', compact('feature'));


    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'value' => 'required',

        ], [
            'title.required' => 'Title is required.',
            'value.required' => 'Value is required.',
        ]);

        $feature = Feature::find($id);
        $feature->update([
            'title' => $request->title,
            'value' => $request->value,
        ]);

        return redirect()->route('admin.features.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Feature updated successfully.'
            ]);
    }

    public function destroy($id)
    {
        $feature = Feature::findOrFail($id);
        $feature->delete();

        return redirect()->route('admin.features.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Feature has been deleted'
            ]);
    }


}

app/Http/Controllers/Backend/GalleryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Gallery;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class GalleryController extends Controller
{
    public function __construct()
    {
    }

    public function index()
    {

        $galleries = Gallery::all();
        return view('backend.gallery.view', compact('galleries'));
    }

    public function create()
    {

        return view('backend.gallery.create');

    }

    public function store(Request $request)
    {

        ini_set('upload_max_filesize', '100M');
        $image = $request->file('file');
        $imageName = $image->getClientOriginalName();
        $image->move(public_path('images/gallery'), $imageName);

        $imageUpload = new Gallery();
        $imageUpload->image = $imageName;
        $imageUpload->save();

        if ($image) {
            return response()->json($image, 200);
        } // Else, return error 400
        else {
            return response()->json('error', 400);
        }
    }

    public function destroy($id)
    {
        $gallery = Gallery::findOrFail($id);
        $filename = $gallery->image;
        Gallery::where('image', $filename)->delete();
        $path = public_path() . '/images/gallery/' . $filename;
        if (file_exists($path)) {
            unlink($path);
        }

        $gallery->delete();
        return redirect()->route('admin.galleries.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Gallery Image has been deleted'
            ]);
    }

    public function destroyGallery(Request $request)
    {
        $filename = $request->get('filename');
        Gallery::where('image', $filename)->delete();
        $path = public_path() . '/images/gallery/' . $filename;
        if (file_exists($path)) {
            unlink($path);
        }
        return $filename;
    }


}

app/Http/Controllers/Backend/GeneralController.php
<?php

namespace App\Http\Controllers\Backend;

use App\General;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;


class GeneralController extends Controller
{
    public function index()
    {
        $general = General::first();
        return view('backend.general.create', compact('general'));
    }

    public function store(Request $request)
    {


        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'shipping_details' => 'required',
            'payment_details' => 'required',
            'return_policy' => 'required',
            'additional_information' => 'required',
        ], [
            'title.required' => 'Title is required.',
            'description.required' => 'Description is required.',
            'shipping_details.required' => 'Shipping Detail is required.',
            'payment_details.required' => 'Payment Details is required.',
            'return_policy.required' => 'Return Policy is required.',
            'additional_information.required' => 'Additional Information is required.'
        ]);
        $general = General::first();
        if (!is_null($general)) {
            $general->update([
                'title' => $request->title,
                'description' => $request->description,
                'shipping_details' => $request->shipping_details,
                'payment_details' => $request->payment_details,
                'return_policy' => $request->return_policy,
                'additional_information' => $request->additional_information,
            ]);
        } else {
            $general = new General();
            $general->title = $request->title;
            $general->description = $request->description;
            $general->shipping_details = $request->shipping_details;
            $general->payment_details = $request->payment_details;
            $general->return_policy = $request->return_policy;
            $general->additional_information = $request->additional_information;
            $general->save();
        }
        return back()->with([
            'flash_status' => 'success',
            'flash_message' => 'Information updated successfully.'
        ]);
    }

}

app/Http/Controllers/Backend/SettingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Setting;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    public function __construct()
    {

    }

    public function index()
    {
        $setting = Setting::first();
        return view('backend.settings.index', compact('setting'));
    }


    public function update(Request $request, $id)
    {
        $setting = Setting::find($id);
        if ($request->has('image')) {
            $image = $request->file('image');
            $name = $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/logo');
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);
            $logo = $name;
        } else {

            $logo = $setting->logo;
        }
        if ($request->has('footer_logo')) {
            $image = $request->file('footer_logo');
            $name = $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/banner');
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);
            $footer_logo = $name;
        } else {
            $footer_logo = $setting->footer_logo;
        }

        $setting->update([
            'status' => $request->status,
            'logo' => $logo,
            'banner' => $footer_logo
        ]);
        return redirect()->route('admin.settings.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Setting updated successfully.'
            ]);

    }
}

resources/views/backend/general/create.blade.php
@extends('layouts.master')
@section('title','General')

@section('content')


    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            {{ __('General') }}
                        </h3>
                    </div>
                </div>
            </div>

            <div class="m-portlet__body">
                <div class="col-lg-12">
                    <div class="m-portlet">
                        <form class="m-form" method="post" action="{{ route('admin.general.store') }}"
                              enctype="multipart/form-data" role="form">
                            @csrf
                            <div class="m-portlet__body">
                                <div class="m-form__section m-form__section--first">


                                    <div class="form-group row">
                                        <div class="col-md-12">


                                            <label for="title"><strong>Title</strong></label>

                                            <textarea name="title" id="title" rows="10" cols="144"
                                                      required>{{ ($general) ? $general->title : '' }}</textarea>

                                            @error('title')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="col-md-12">


                                            <label for="description"><strong>Description</strong></label>

                                            <textarea name="description" id="description" rows="10" cols="80"
                                                      required>{{ ($general) ? $general->description : '' }}</textarea>

                                            @error('description')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="col-md-12">


                                            <label for="shipping_details"><strong>Shipping Details</strong></label>

                                            <textarea name="shipping_details" id="shipping_details" rows="10" cols="80"
                                                      required>{{ ($general) ? $general->shipping_details : '' }}</textarea>

                                            @error('shipping_details')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="col-md-12">


                                            <label for="payment_details"><strong>Payment Details</strong></label>

                                            <textarea name="payment_details" id="payment_details" rows="10" cols="80"
                                                      required>{{ ($general) ? $general->payment_details : '' }}</textarea>

                                            @error('payment_details')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="col-md-12">


                                            <label for="return_policy"><strong>Return Policy</strong></label>

                                            <textarea name="return_policy" id="return_policy" rows="10" cols="80"
                                                      required>{{ ($general) ? $general->return_policy : '' }}</textarea>

                                            @error('return_policy')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="col-md-12">


                                            <label for="additional_information"><strong>Additional Information</strong></label>

                                            <textarea name="additional_information" id="additional_information"
                                                      rows="10" cols="80"
                                                      required>{{ ($general) ? $general->additional_information : '' }}</textarea>

                                            @error('additional_information')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                    </div>


                                </div>
                            </div>
                            <div class="m-portlet__foot m-portlet__foot--fit text-md-right">
                                <div class="m-form__actions m-form__actions">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('SAVE') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>
        </div>
    </div>
@endsection