routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');

    return 'Commands run successfully Cleared.';
});
Route::get('/', function () {

    return view('welcome');

})->name('index');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/about-us', 'FrontendController@about')->name('about');
Route::get('/services', 'FrontendController@services')->name('services');
Route::get('/contact-us', 'FrontendController@contactUs')->name('contact-us');

Route::get('forget-password', 'AccountController@getEmail');
Route::post('forget-password', 'AccountController@postEmail');
Route::get('reset-password/{token}', 'AccountController@getPassword');
Route::post('reset-password', 'AccountController@updatePassword');


Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/galleries', 'Backend\GalleryController');
        Route::post('single/gallery/delete', 'Backend\GalleryController@destroyGallery')->name('single.gallery.destroy');
        Route::resource('/features', 'Backend\FeatureController');
        Route::resource('/general', 'Backend\GeneralController', [
            'only' => ['index', 'store']
        ]);
        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'update']
        ]);
    });
});

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $table = "galleries";
    protected $guarded = [];

    public function getImagePathAttribute()
    {
        return asset('images/gallery/' . $this->image);
    }
}

app/Http/Controllers/Backend/FeatureController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Feature;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;


class FeatureController extends Controller
{


    public function index()
    {
        $features = Feature::orderBy('id', 'ASC')->get();
        return view('backend.features.index', compact('features'));
    }

    public function create()
    {
        return view('backend.features.create');
    }

    public function store(Request $request)
    {

        $this->validate($request, [
            'title' => 'required',
            'value' => 'required',

        ], [
            'title.required' => 'Title is required.',
            'value.required' => 'Value is required.',
        ]);


        $feature = Feature::create([
            'title' => $request->title,
            'value' => $request->value,
        ]);

        return redirect()->route('admin.features.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Feature created successfully.'
            ]);
    }

    public function edit($id)
    {
        $feature = Feature::find($id);
        return view('backend.features.edit', compact('feature'));


    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'value' => 'required',

        ], [
            'title.required' => 'Title is required.',
            'value.required' => 'Value is required.',
        ]);

        $feature = Feature::find($id);
        $feature->update([
            'title' => $request->title,
            'value' => $request->value,
        ]);

        return redirect()->route('admin.features.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Feature updated successfully.'
            ]);
    }

    public function destroy($id)
    {
        $feature = Feature::findOrFail($id);
        $feature->delete();

        return redirect()->route('admin.features.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Feature has been deleted'
            ]);
    }


}

app/Http/Controllers/Backend/GalleryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Gallery;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class GalleryController extends Controller
{
    public function __construct()
    {
    }

    public function index()
    {

        $galleries = Gallery::all();
        return view('backend.gallery.view', compact('galleries'));
    }

    public function create()
    {

        return view('backend.gallery.create');

    }

    public function store(Request $request)
    {

        ini_set('upload_max_filesize', '100M');
        $image = $request->file('file');
        $imageName = $image->getClientOriginalName();
        $image->move(public_path('images/gallery'), $imageName);

        $imageUpload = new Gallery();
        $imageUpload->image = $imageName;
        $imageUpload->save();

        if ($image) {
            return response()->json($image, 200);
        } // Else, return error 400
        else {
            return response()->json('error', 400);
        }
    }

    public function destroy($id)
    {
        $gallery = Gallery::findOrFail($id);
        $filename = $gallery->image;
        Gallery::where('image', $filename)->delete();
        $path = public_path() . '/images/gallery/' . $filename;
        if (file_exists($path)) {
            unlink($path);
        }

        $gallery->delete();
        return redirect()->route('admin.galleries.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Gallery Image has been deleted'
            ]);
    }

    public function destroyGallery(Request $request)
    {
        $filename = $request->get('filename');
        Gallery::where('image', $filename)->delete();
        $path = public_path() . '/images/gallery/' . $filename;
        if (file_exists($path)) {
            unlink($path);
        }
        return $filename;
    }


}

app/Http/Controllers/Backend/GeneralController.php
<?php

namespace App\Http\Controllers\Backend;

use App\General;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;


class GeneralController extends Controller
{
    public function index()
    {
        $general = General::first();
        return view('backend.general.create', compact('general'));
    }

    public function store(Request $request)
    {


        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'shipping_details' => 'required',
            'payment_details' => 'required',
            'return_policy' => 'required',
            'additional_information' => 'required',
        ], [
            'title.required' => 'Title is required.',
            'description.required' => 'Description is required.',
            'shipping_details.required' => 'Shipping Detail is required.',
            'payment_details.required' => 'Payment Details is required.',
            'return_policy.required' => 'Return Policy is required.',
            'additional_information.required' => 'Additional Information is required.'
        ]);
        $general = General::first();
        if (!is_null($general)) {
            $general->update([
                'title' => $request->title,
                'description' => $request->description,
                'shipping_details' => $request->shipping_details,
                'payment_details' => $request->payment_details,
                'return_policy' => $request->return_policy,
                'additional_information' => $request->additional_information,
            ]);
        } else {
            $general = new General();
            $general->title = $request->title;
            $general->description = $request->description;
            $general->shipping_details = $request->shipping_details;
            $general->payment_details = $request->payment_details;
            $general->return_policy = $request->return_policy;
            $general->additional_information = $request->additional_information;
            $general->save();
        }
        return back()->with([
            'flash_status' => 'success',
            'flash_message' => 'Information updated successfully.'
        ]);
    }

}

app/Http/Controllers/Backend/SettingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Setting;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    public function __construct()
    {

    }

    public function index()
    {
        $setting = Setting::first();
        return view('backend.settings.index', compact('setting'));
    }


    public function update(Request $request, $id)
    {
        $setting = Setting::find($id);
        if ($request->has('image')) {
            $image = $request->file('image');
            $name = $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/logo');
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);
            $logo = $name;
        } else {

            $logo = $setting->logo;
        }
        if ($request->has('footer_logo')) {
            $image = $request->file('footer_logo');
            $name = $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/banner');
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);
            $footer_logo = $name;
        } else {
            $footer_logo = $setting->footer_logo;
        }

        $setting->update([
            'status' => $request->status,
            'logo' => $logo,
            'banner' => $footer_logo
        ]);
        return redirect()->route('admin.settings.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Setting updated successfully.'
            ]);

    }
}

resources/views/backend/gallery/create.blade.php
@extends('layouts.master')
@section('title','Gallery')
@push('css')
    <style>

        .m-portlet textarea {
            height: 100% !important;
        }
    </style>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.0/min/dropzone.min.css">


@endpush
@push('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.0/dropzone.js"></script>
@endpush
@section('content')


    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Add {{ __('Gallery') }}
                        </h3>
                    </div>
                </div>
            </div>

            <div class="m-portlet__body">
                <div class="col-lg-12">
                    <div class="m-portlet">
                        <form method="post" action="{{route('admin.galleries.store')}}"
                              enctype="multipart/form-data"
                              class="dropzone m-form" id="dropzone">
                            @csrf
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')

    <script type="text/javascript">

        Dropzone.options.dropzone =
            {
                addRemoveLinks: true,
                acceptedFiles: ".jpeg,.jpg,.png,.gif",
                maxFiles: 20,
                maxFilesize: 1,//max file size in MB,
                renameFile: function (file) {
                    var dt = new Date();
                    var time = dt.getTime();
                    return time + file.name;
                },
                init: function () {
                    this.on("error", function (file, message) {
                        toastr.success(message, 'Error Alert', {
                            timeOut: 5000
                        });
                        this.removeFile(file);
                    });
                },
                removedfile: function (file) {
                    var name = file.upload.filename;
                    $.ajax({
                        headers: {
                            'X-CSRF-TOKEN': '{{ csrf_token() }}'
                        },
                        type: 'POST',
                        url: '{{ route('admin.single.gallery.destroy') }}',
                        data: {filename: name},
                        success: function (data) {
                            toastr.success('File has been successfully removed!!', 'Success Alert', {
                                timeOut: 5000
                            });
                        },
                        error: function (e) {
                            toastr.success(e, 'Error Alert', {
                                timeOut: 5000
                            });
                        }
                    });
                    var fileRef;
                    return (fileRef = file.previewElement) != null ?
                        fileRef.parentNode.removeChild(file.previewElement) : void 0;
                },
                success: function (file, response) {
                    toastr.success('File has been successfully Added!!', 'Success Alert', {
                        timeOut: 5000
                    });
                },
                error: function (file, response) {
                    toastr.success('Something Went Wrong', 'Error Alert', {
                        timeOut: 5000
                    });
                }
            };
    </script>
@endpush

resources/views/backend/gallery/view.blade.php
@extends('layouts.master')
@section('title','Gallery')
@push('css')
    <style>
        #comments {
            width: 95%;
            height: 100px;
        }

        .commentLabel {
            float: left;
            margin-left: 11px;
            margin-top: 12px;
        }
    </style>
@endpush
@section('content')

    <div class="m-content">
        <!--Begin::Section-->
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Gallery
                        </h3>
                    </div>
                </div>
                <div class="m-portlet__head-tools">
                    <ul class="m-portlet__nav">
                        <li class="m-portlet__nav-item">
                            <a href="{{ route('admin.galleries.create') }}"
                               class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                <span>
                                    <i class="la la-plus"></i>
                                    <span>Add Gallery</span>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>


            </div>

            <div class="m-portlet__body">
                <input type="hidden">

                <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                    <thead>
                    <tr>

                        <th>Sr No.</th>
                        <th>Image</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(!empty($galleries))
                        @foreach($galleries as $gallery)

                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td><img width="300" height="200" class="img-thumbnail"
                                         style="display:{{($gallery->image) ? '' : 'none'}}; max-width: 100%"
                                         id="img"
                                         src="{{ $gallery->image_path}}"
                                         alt="your image"/></td>
                                <td nowrap style="width: 12%;">


                                    <form method="post"
                                          action="{{ route('admin.galleries.destroy', $gallery->id) }}"
                                          id="delete_{{ $gallery->id }}">
                                        @csrf
                                        @method('DELETE')
                                        <a class="btn btn-sm btn-danger m-left"
                                           href="javascript:void(0)"
                                           onclick="if(confirmDelete()){ document.getElementById('delete_<?=$gallery->id?>').submit(); }">
                                            Delete
                                        </a>
                                    </form>
                                </td>
                            </tr>

                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@push('models')

@endpush
@push('js')
    <script>
        $("#m_table_1").dataTable({
            "ordering": false,
            "order": [[0, "desc"]],
            "columnDefs": [
                {orderable: false, targets: [2]}
            ],
        });

    </script>
@endpush